services:
  dev:
    image: node:20
    container_name: react-dev
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:3000"
    command: sh -c "npm install && npm run dev -- --hostname 0.0.0.0"

  release:
    image: node:20
    container_name: react-release
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build"