services:
  dev:
    image: node:20
    container_name: react-dev
    working_dir: /app
    user: "1000:1000"
    volumes:
      - ./:/app
    ports:
      - "8080:3000"
    command: sh -c "npm install && npm run build && npx serve out"

  release:
    image: node:20
    container_name: react-release
    working_dir: /app
    user: "1000:1000"
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build"